# Generated by Django 4.1.3 on 2022-12-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cessaofundo',
            name='ccb',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cessaofundo',
            name='doc_cedente',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cessaofundo',
            name='id_externo',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cessaofundo',
            name='parcela',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cessaofundo',
            name='total_parcelas',
            field=models.BigIntegerField(default=0),
        ),
    ]
